import mongoose from "mongoose";

const tradeSchema = new mongoose.Schema(
  {
    signal: { type: String, required: true },
    strategyVersion: { type: String, default: "v2-research", index: true },
    managementPlan: { type: String, default: null, index: true },
    score: { type: Number, default: 0 },
    entry: Number,
    currentPrice: Number,
    stopLoss: Number,
    originalStopLoss: Number,
    takeProfit1: Number,
    takeProfit2: Number,
    riskPoints: { type: Number, default: 0 },
    rewardPoints: { type: Number, default: 0 },
    pnlPoints: { type: Number, default: 0 },
    result: { type: String, default: "OPEN" },
    tradeJourney: { type: String, default: "OPEN" },
    status: { type: String, default: "ACTIVE" },
    openTime: Number,
    closeTime: Number,
    tradeDurationSeconds: { type: Number, default: 0 },
    tp1Hit: { type: Boolean, default: false },
    tp2Hit: { type: Boolean, default: false },
    tp1Locked: { type: Boolean, default: false },
    tp1LockTime: Number,
    highestProfitPoints: { type: Number, default: 0 },
    lowestDrawdownPoints: { type: Number, default: 0 },
    maxFavorablePrice: { type: Number, default: 0 },
    maxAdversePrice: { type: Number, default: 0 },
    buyPressure: { type: Number, default: 0 },
    sellPressure: { type: Number, default: 0 },
    trend: String,
    bullishEMA: { type: Boolean, default: false },
    bearishEMA: { type: Boolean, default: false },
    ema200: Number,
    emaDistancePoints: Number,
    atr: Number,
    volumeRatio: Number,
    volumeSpike: { type: Boolean, default: false },
    liquidity: { type: Boolean, default: false },
    liquidityType: String,
    liquiditySweptLevel: Number,
    session: { type: Boolean, default: false },
    utcHour: Number,
    dayOfWeek: Number,
    bos: String,
    choch: String,
  },
  { timestamps: true }
);

export default mongoose.model("Trade", tradeSchema);
